# Generated by Django 2.1.7 on 2020-05-15 06:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Community_Name', models.CharField(max_length=64)),
                ('CreateDate', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='GoodReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Body', models.TextField()),
                ('Post_time', models.DateTimeField(default=datetime.datetime.now)),
                ('SoftDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribtion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Communities')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('Post_time', models.DateTimeField(default=datetime.datetime.now)),
                ('SoftDelete', models.BooleanField(default=False)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Thread')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='Body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Title',
        ),
        migrations.AddField(
            model_name='post',
            name='Post_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='post',
            name='SoftDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upvote',
            name='P_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Post'),
        ),
        migrations.AddField(
            model_name='upvote',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='P_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Post'),
        ),
        migrations.AddField(
            model_name='reply',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodreply',
            name='P_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Post'),
        ),
        migrations.AddField(
            model_name='goodreply',
            name='T_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Thread'),
        ),
        migrations.AddField(
            model_name='goodreply',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='T_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Login.Thread'),
        ),
    ]
