# Generated by Django 2.1.7 on 2020-06-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20200515_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communities',
            name='CreateDate',
        ),
    ]
